# Generated by Django 5.2 on 2025-06-02 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='currency',
            field=models.CharField(blank=True, choices=[('USD', 'USD'), ('USZ', 'USZ')], default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='contact',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('converted', 'Converted'), ('failed', 'Failed')], default='new', max_length=20),
        ),
    ]
