# Generated by Django 5.2 on 2025-06-02 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('UZS', 'UZS')], max_length=10),
        ),
        migrations.AlterField(
            model_name='deal',
            name='status',
            field=models.CharField(choices=[('open', 'New'), ('won', 'Done'), ('lost', 'Lose')], max_length=10),
        ),
    ]
